### ISSUE TITLE
Config Global Called in function

### ISSUE THREAD

**Issue by jgockley62** [PradoVarathan/metanetwork#5]
Both Aracne.R and installAracne.R.R call `config$input_profile$temp_storage_loc` from global environment instead of passed to function as arguments. 

Lines: 
https://github.com/PradoVarathan/metanetwork/blob/da07c4466f179fd7f1787591dc062e97eb902262/R/aracne.R#L35
https://github.com/PradoVarathan/metanetwork/blob/da07c4466f179fd7f1787591dc062e97eb902262/R/installAracne.R#L16

**Comment by PradoVarathan** [comment]
Yup! I can modify that in the function and run the git hub actions accordingly!
